name: Bump Version

on:
  pull_request:
    paths:
      - 'cloudflared.version'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      # strictly required for the bot to push
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          # Uses the default GITHUB_TOKEN automatically
          ref: ${{ github.head_ref }}

      - uses: pypa/hatch@install

      - name: Bump Version
        run: hatch version minor

      - name: Commit Change Back to PR
        id: auto-commit
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump python version to match cloudflared"
          file_pattern: "src/*/__about__.py"

      # Add this step immediately after to FORCE failure if nothing happened
      - name: Fail if no changes
        if: steps.auto-commit.outputs.changes_detected == 'false'
        run: |
          echo "::error::No changes were detected! Either 'hatch version' failed to modify the file, or the file_pattern 'src/*/__about__.py' is incorrect."
          exit 1

  ci:
    needs: bump-version
    uses: ./.github/workflows/ci.yml
