name: Bump Version

on:
  pull_request:
    paths:
      - 'cloudflared.version'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      # strictly required for the bot to push
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          # Uses the default GITHUB_TOKEN automatically
          ref: ${{ github.head_ref }}

      - uses: pypa/hatch@install

      - name: Bump Version
        run: hatch version minor

      - name: Commit Change Back to PR
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: bump python version to match cloudflared"
          file_pattern: "src/pyflared/__about__.py"