name: ci
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'cloudflared.version'
  workflow_dispatch: # UI button
  workflow_call: # Make callable by other workflows
  workflow_run: # Chain after another workflow
    workflows: [ "Bump Version" ]
    types:
      - completed



jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      # 1. Bring your code onto the runner
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Hatch
        uses: pypa/hatch@install

      - name: Bump version
        run: hatch version patch

      - name: Run tests
        run: hatch test -- -s

  test-report:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "All good!"


#  build-on-arm:
#    runs-on: ubuntu-24.04-arm     # ‚Üê valid & recommended
#
#    steps:
#      #      - uses: actions/checkout@v4
#      #      -
#      - run: uname -m               # outputs: aarch64
#      - run: lsb_release -a         # shows Ubuntu 24.04 details
